apiVersion: v1
kind: Service
metadata:
  name: angular-service
  namespace: capstone
  labels:
    name: angular-service
    tier: frontend
spec:
  ports:
    - nodePort: 32100 
      port: 80        
      targetPort: 80  
      protocol: TCP   
  selector:           
    app: angular
    tier: frontend
  type: LoadBalancer