apiVersion: apps/v1 
kind: Deployment    
metadata:
  namespace: capstone            
  name: angular
spec:              
  selector:   
    matchLabels:
      app: angular
      tier: frontend
  replicas: 1        
  template:
    metadata:
      labels:      
        app: angular
        tier: frontend
    spec:
      containers:
        - name: angular
          image: himanshuchaudhary/angular-app:5
          imagePullPolicy: Always
          ports:
            - containerPort: 80