apiVersion: apps/v1 
kind: Deployment    
metadata:
  namespace: capstone            
  name: angular
spec:              
  selector:   
    matchLabels:
      app: angular
  replicas: 1        
  template:
    metadata:
      labels:      
        app: angular
    spec:
      containers:
        - name: angular
          image: himanshuchaudhary/angular-app:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
    apiVersion: v1
    kind: Service
    metadata:
      name: angular-service
      namespace: capstone
      labels:
        name: angular-deployment
    spec:
      ports:
        - nodePort: 32100 
          port: 80        
          targetPort: 80  
          protocol: TCP   
      selector:           
        app: angular
      type: LoadBalancer    
